dist: trust
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - ARCH=i386
  - ARCH=amd64
os:
  - linux
  # TODO(dcreager): Reenable this once the Travis Mac backlog isn't quite so
  # horrific.
  # - osx
install: .travis/install
script: .travis/test

# In addition to pull requests, always build these branches
branches:
  only:
    - master
    - develop
