# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# Copyright © 2012, RedJack, LLC.
# All rights reserved.
#
# Please see the COPYING file in this distribution for license details.
# ----------------------------------------------------------------------

from distutils.core import setup
from version import get_git_version

version = get_git_version()

# Make the current version number available in the library.
version_py = open("buzzy/version.py", "w")
version_py.write("""
# AUTOGENERATED FILE.  DO NOT EDIT.
version = "%s"
""" % version)

setup(
    name='buzzy',
    version=version,
    description="OS-agnostic package builder",
    author="Douglas Creager",
    author_email="douglas.creager@redjack.com",
    url="https://github.com/redjack/buzzy/",
    packages=[
        'buzzy',
        'buzzy.build',
        'buzzy.command',
        'buzzy.distro',
        'buzzy.source',
    ],
    scripts=['scripts/buzzy'],
    requires=["PyYAML"],
)
