#!/bin/sh

SCRIPT=`python -c "import os; print(os.path.realpath('$0'))"`
SCRIPT_DIR=`dirname "$SCRIPT"`

for DISTRO in `cat $SCRIPT_DIR/all`; do
    echo
    echo "--------------------------------------"
    echo $DISTRO
    echo "--------------------------------------"
    echo
    "$SCRIPT_DIR/build" "$DISTRO"
done
