#!/usr/bin/python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# Copyright © 2012, RedJack, LLC.
# All rights reserved.
#
# Please see the COPYING file in this distribution for license details.
# ----------------------------------------------------------------------

if __name__ == "__main__":
    import buzzy.cmd
    import sys
    buzzy.cmd.main(sys.argv[1:])
