#!/usr/bin/python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# Copyright © 2012, RedJack, LLC.
# All rights reserved.
#
# Please see the COPYING file in this distribution for license details.
# ----------------------------------------------------------------------

if __name__ == "__main__":
    import buzzy.commands
    from buzzy.errors import BuzzyError
    import sys
    try:
        buzzy.commands.main(sys.argv[1:])
    except BuzzyError as e:
        e.print()
        sys.exit(1)
